### PR TITLE
fixing autoload and namespace

### PR DESCRIPTION
**Pull request by liuggio**
moved out of composer the namespaces for tests.

### CODE REVIEW

**Comment by liuggio** [comment]
News on it?
pro, cons?

**Comment by odino** [comment]
@cirpo?

I have nothing against this, but I also dunno if its better to put the configuration in the bootstrap file or in the composer json file

**Comment by liuggio** [comment]
Putting it into composer means the scope is to the high level (other dep could see those classes), with this PR only when you execute the bootstrap those classes are loaded (suggested).

**Comment by odracci** [comment]
+1

**Comment by odino** [comment]
I am still not convinced but will merge it as it seems it makes sense to others

cheers!

**Comment by liuggio** [comment]
> I am still not convinced

this is a library, do you want to expose tests in production for the end-user?

**Comment by odino** [comment]
They will download it anyhow, and the IDE would show them, isnt it? I think best would be to be able to download the library itself without tests, that would fix the root issue

I see your point but its ineffective as of now with the current state of composer, right?

**Comment by liuggio** [comment]
Composer will not put the tests in the autoloader.
1. Saving processing time
2. The user from his/her classes could not use AOP/Tests/

:)

**Comment by odino** [comment]
As I said, I see your point, but then you have the IDE which would still see those classes, making this change less effective :( processing time it's not a big deal to me

**Comment by liuggio** [comment]
You should make a PR to your IDE, it is not showing the correct classes :)

**Pull request merged**
